version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  yarn-exporter:
    build: ./yarn-exporter
    ports:
      - "9115:9115"
    environment:
      - YARN_API_URL=${YARN_API_URL}
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    volumes:
    - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    - ./grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/main.yaml
    - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring: