{
 "title": "Yarn Cluster",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Yarn Apps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "yarn_cluster_metrics_appsRunning",
     "legendFormat": "Running"
    },
    {
     "expr": "yarn_cluster_metrics_appsPending",
     "legendFormat": "Pending"
    },
    {
     "expr": "increase(yarn_cluster_metrics_appsKilled [1m])/2",
     "legendFormat": "Killed"
    },
    {
     "expr": "increase(yarn_cluster_metrics_appsFailed [1m])/2",
     "legendFormat": "Failed (Increase)"
    },
    {
     "expr": "increase(yarn_cluster_metrics_appsCompleted [1m])/2",
     "legendFormat": "Completed (Increase)"
    },
    {
     "expr": "increase(yarn_cluster_metrics_appsSubmitted [1m])/2",
     "legendFormat": "Submitted (Increase)"
    }
   ]
  },
  {
   "title": "Yarn Apps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarn_cluster_metrics_appsRunning",
     "legendFormat": "Running"
    },
    {
     "expr": "yarn_cluster_metrics_appsPending",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "yarn_cluster_metrics_containersAllocated",
     "legendFormat": "Allocated"
    },
    {
     "expr": "yarn_cluster_metrics_containersPending",
     "legendFormat": "Pending"
    },
    {
     "expr": "yarn_cluster_metrics_containersReserved",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarn_cluster_metrics_containersAllocated",
     "legendFormat": "Allocated"
    },
    {
     "expr": "yarn_cluster_metrics_containersPending",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Mem Used/Reserved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "yarn_cluster_metrics_totalMB", "legendFormat": "Total MB" },
    {
     "expr": "yarn_cluster_metrics_allocatedMB",
     "legendFormat": "Allocated MB"
    },
    {
     "expr": "yarn_cluster_metrics_reservedMB",
     "legendFormat": "Reserved MB"
    }
   ]
  },
  {
   "title": "CPU Used/Reserved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "yarn_cluster_metrics_totalVirtualCores",
     "legendFormat": "Total vCores"
    },
    {
     "expr": "yarn_cluster_metrics_allocatedVirtualCores",
     "legendFormat": "Used vCores"
    },
    {
     "expr": "yarn_cluster_metrics_reservedVirtualCores",
     "legendFormat": "Reserved vCores"
    }
   ]
  }
 ]
}